cc_binary(
  name = "microloop_usage",
  srcs = ["microloop_usage.cpp"],
  deps = [
    "//lib/microloop:microloop",
  ],
)

cc_binary(
  name = "static_server",
  srcs = ["static_server.cpp"],
  deps = [
    "//lib/microhttp:microhttp",
    "//lib/microloop:microloop",
  ],
)

cc_binary(
  name = "request_parser_example",
  srcs = ["request_parser_example.cpp"],
  deps = [
    "//lib/microhttp:microhttp",
    "//lib/microloop:microloop",
  ],
)

cc_binary(
  name = "playground",
  srcs = ["playground.cpp"],
  deps = [
    "//lib/microloop:microloop",
    "//lib/microhttp:microhttp",
    "//lib/uri:uri",
  ],
)
