cc_binary(
  name = "microloop_usage",
  srcs = ["microloop_usage.cpp"],
  deps = [
    "//lib/microloop:microloop",
  ],
)

cc_binary(
  name = "request_parser_example",
  srcs = ["request_parser_example.cpp"],
  deps = [
    "//lib/microhttp:microhttp",
  ],
)
