cc_test(
  name = "buffer",
  timeout = "short",
  srcs = ["buffer_test.cpp"],
  deps = [
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "//lib/microloop:microloop",
  ],
)

test_suite(name = "full")
