cc_test(
  name = "string_starts_with",
  timeout = "short",
  srcs = ["string_starts_with_test.cpp"],
  deps = [
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "//lib/utils:utils",
  ],
)

cc_test(
  name = "string_ends_with",
  timeout = "short",
  srcs = ["string_ends_with_test.cpp"],
  deps = [
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "//lib/utils:utils",
  ],
)
