cc_library(
  name = "microhttp",
  srcs = glob(["src/**/*.cpp"]),
  hdrs = glob(["include/**/*.h"]),
  includes = [
    "include",
  ],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/microloop:microloop",
  ],
)
